INSERT INTO User (ID, HASLOANS, NAME)
VALUES (1, false, 'k');
INSERT INTO User (HASLOANS, NAME)
VALUES (false, 'l');
INSERT INTO Book (ID, LOAN_ID)
VALUES (1, null);
INSERT INTO Book (ID, LOAN_ID)
VALUES (2, null);